# apiVersion: v1
# kind: Service
# metadata:
#   name: svc-app-vagner
#   labels:
#     app: app-vagner
#     service: details
# spec:
#   ports:
#   - port: 80
#     name: http
#   selector:
#     app: app-vagner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-vagner
  labels:
    app: app-vagner
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-vagner
      version: v1
  template:
    metadata:
      labels:
        app: app-vagner
        version: v1
    spec:
      containers:
      - name: app-vagner
        image: docker.io/mnoskoski/app-vagner
        env:
          - name: NODE_ENV
            value: "Development"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80