apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-vagner
    version: v1
  name: app-vagner
  namespace: ns-app-vagner
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: app-vagner
    version: v1
  type: LoadBalancer